server {
	listen 8080;
	root /home/slava/Projects/Webserv/www;
	client_max_body_size 1048576;
	error_page 404 /home/slava/Projects/Webserv/www/errors/404.html;

	location / {
		allowed_methods GET POST DELETE;
		autoindex on;
		index index.html;
		upload_enabled on;
		upload_dir /home/slava/Projects/Webserv/www/uploads;
	}
}
