server {
	listen 8080;
	root /home/dev/dev/projects/WebServ/www;
	client_max_body_size 1048576;
	error_page 404 /home/slava/Projects/WebServ/www/errors/404.html;

	location / {
		allowed_methods GET POST DELETE;
		autoindex on;
		index index.html;
		upload_enabled on;
		upload_dir /home/dev/dev/projects/WebServ/www/uploads;
	}

	location /old {
		allowed_methods GET;
		return 301 /about/;
	}

	location /cgi-bin {
    root ./www/cgi-bin;
    allowed_methods GET POST;
    cgi .py;
	}
}
